# Generated by Django 3.1.1 on 2020-12-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temprature', '0002_auto_20201221_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
