# Generated by Django 3.1.1 on 2020-12-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temprature', '0003_auto_20201221_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=16)),
                ('workgroup', models.CharField(max_length=16)),
                ('make', models.CharField(max_length=16)),
                ('mac', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ipaddress', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Speedtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField()),
                ('sponsor', models.CharField(max_length=16)),
                ('servername', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('ping', models.DecimalField(decimal_places=4, max_digits=16)),
                ('download', models.DecimalField(decimal_places=4, max_digits=16)),
                ('upload', models.DecimalField(decimal_places=4, max_digits=16)),
                ('share', models.CharField(max_length=8)),
                ('ipaddress', models.CharField(max_length=16)),
            ],
        ),
    ]
