# Generated by Django 3.1.1 on 2020-12-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temprature', '0004_devices_online_speedtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtest',
            name='servername',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='speedtest',
            name='sponsor',
            field=models.CharField(max_length=32),
        ),
    ]
